//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesarrolloBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puesto_trabajo
    {
        public int Id_Pue { get; set; }
        public int Id_Loc { get; set; }
        public int Id_Ar { get; set; }
        public int Id_Em { get; set; }
        public int Id_Cues { get; set; }
        public string Documento_identidad { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<decimal> MedidaVisual { get; set; }
        public string ResultadoMedidaVisual { get; set; }
        public Nullable<decimal> MedidaAuditiva { get; set; }
        public string ResultadoMedidaAuditiva { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Local Local { get; set; }
    }
}
